#ifndef LIMEENUMS_HPP
#define LIMEENUMS_HPP

#include "unordered_map"
#define REGISTER_LIMEENUM(x,y) { gEnumStr2Int.insert(std::pair<const char*, int>(#x,y)); gEnumInt2Str.insert(std::pair<int, const char*>(y,#x));}


/*
namespaces
------------
LIMEENUMS_MOUSEBUTTONS
LIMEENUMS_EVENTID
LIMEENUMS_PLAYERSTATES
LIMEENUMS_CAMERAMOVEMENTS
LIMEENUMS_SDL_SCANCODES
*/



namespace LIMEENUMS_MOUSEBUTTONS {
    inline std::unordered_map<const char*, int> gEnumStr2Int;
    inline std::unordered_map<int, const char*> gEnumInt2Str;

    inline void stringify() {
        REGISTER_LIMEENUM(LB,0)
        REGISTER_LIMEENUM(MB,0)
        REGISTER_LIMEENUM(RB,0)
        REGISTER_LIMEENUM(TOTAL,0)
    }
}

namespace LIMEENUMS_EVENTID {
    inline std::unordered_map<const char*, int> gEnumStr2Int;
    inline std::unordered_map<int, const char*> gEnumInt2Str;


    inline void stringify(){
        // WINDOW
        REGISTER_LIMEENUM(E_WINDOW_QUIT,0)
        REGISTER_LIMEENUM(E_WINDOW_RESIZED,1)
            REGISTER_LIMEENUM(P_WINDOW_RESIZED_WIDTH,2)
            REGISTER_LIMEENUM(P_WINDOW_RESIZED_HEIGHT,3)
        // KEYBOARD
        REGISTER_LIMEENUM(E_WINDOW_KEY_PRESSED,4)
            REGISTER_LIMEENUM(P_WINDOW_KEY_PRESSED_KEYCODE,5)
        REGISTER_LIMEENUM(E_WINDOW_KEY_RELEASED,6)
            REGISTER_LIMEENUM(P_WINDOW_KEY_RELEASED_KEYCODE,7)
        REGISTER_LIMEENUM(E_WINDOW_KEY_TRIGGERED,8)
            REGISTER_LIMEENUM(P_WINDOW_KEY_TRIGGERED_KEYCODE,9)
        // MOUSE
        REGISTER_LIMEENUM(E_WINDOW_MOUSE_MOVE,10)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_MOVE_X,11)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_MOVE_Y,12)
        REGISTER_LIMEENUM(E_WINDOW_MOUSE_DOWN,13)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_DOWN_BUTTON,14)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_DOWN_X,15)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_DOWN_Y,16)
        REGISTER_LIMEENUM(E_WINDOW_MOUSE_UP,17)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_UP_BUTTON,18)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_UP_X,19)
            REGISTER_LIMEENUM(P_WINDOW_MOUSE_UP_Y,20)
        // GRAPHICS
        REGISTER_LIMEENUM(E_GRAPHICS_DEBUG_TOGGLE,21)
        // CAMERA
        REGISTER_LIMEENUM(E_GRAPHICS_CAMERA_UPDATED,22)
            REGISTER_LIMEENUM(P_GRAPHICS_CAMERA_UPDATED_ENTITYID,23)
        REGISTER_LIMEENUM(EP_TOTAL,24)
    }
}

namespace LIMEENUMS_PLAYERSTATES {
    inline std::unordered_map<const char*, int> gEnumStr2Int;
    inline std::unordered_map<int, const char*> gEnumInt2Str;

    inline void stringify() {
        REGISTER_LIMEENUM(PS_IDLE,0)
        REGISTER_LIMEENUM(PS_RUN,1)
        REGISTER_LIMEENUM(PS_JUMP,2)
        REGISTER_LIMEENUM(PS_GLIDE,3)
        REGISTER_LIMEENUM(PS_GROUND,4)
        REGISTER_LIMEENUM(PS_TOTAL,5)
    }
}

namespace LIMEENUMS_CAMERAMOVEMENTS {
    inline std::unordered_map<const char*, int> gEnumStr2Int;
    inline std::unordered_map<int, const char*> gEnumInt2Str;

    inline void stringify() {
        REGISTER_LIMEENUM(CM_FORWARD,0)
        REGISTER_LIMEENUM(CM_BACKWARD,1)
        REGISTER_LIMEENUM(CM_LEFT,2)
        REGISTER_LIMEENUM(CM_RIGHT,3)
        REGISTER_LIMEENUM(CM_UP,4)
        REGISTER_LIMEENUM(CM_DOWN,5)
        REGISTER_LIMEENUM(CM_TOTAL,6)
    }
}


namespace LIMEENUMS_SDL_SCANCODES {

    inline std::unordered_map<const char*, int> gEnumStr2Int;
    inline std::unordered_map<int, const char*> gEnumInt2Str;


    inline void stringify() {
        REGISTER_LIMEENUM(SDL_SCANCODE_UNKNOWN, 0)
            REGISTER_LIMEENUM(SDL_SCANCODE_A, 4)
            REGISTER_LIMEENUM(SDL_SCANCODE_B, 5)
            REGISTER_LIMEENUM(SDL_SCANCODE_C, 6)
            REGISTER_LIMEENUM(SDL_SCANCODE_D, 7)
            REGISTER_LIMEENUM(SDL_SCANCODE_E, 8)
            REGISTER_LIMEENUM(SDL_SCANCODE_F, 9)
            REGISTER_LIMEENUM(SDL_SCANCODE_G, 10)
            REGISTER_LIMEENUM(SDL_SCANCODE_H, 11)
            REGISTER_LIMEENUM(SDL_SCANCODE_I, 12)
            REGISTER_LIMEENUM(SDL_SCANCODE_J, 13)
            REGISTER_LIMEENUM(SDL_SCANCODE_K, 14)
            REGISTER_LIMEENUM(SDL_SCANCODE_L, 15)
            REGISTER_LIMEENUM(SDL_SCANCODE_M, 16)
            REGISTER_LIMEENUM(SDL_SCANCODE_N, 17)
            REGISTER_LIMEENUM(SDL_SCANCODE_O, 18)
            REGISTER_LIMEENUM(SDL_SCANCODE_P, 19)
            REGISTER_LIMEENUM(SDL_SCANCODE_Q, 20)
            REGISTER_LIMEENUM(SDL_SCANCODE_R, 21)
            REGISTER_LIMEENUM(SDL_SCANCODE_S, 22)
            REGISTER_LIMEENUM(SDL_SCANCODE_T, 23)
            REGISTER_LIMEENUM(SDL_SCANCODE_U, 24)
            REGISTER_LIMEENUM(SDL_SCANCODE_V, 25)
            REGISTER_LIMEENUM(SDL_SCANCODE_W, 26)
            REGISTER_LIMEENUM(SDL_SCANCODE_X, 27)
            REGISTER_LIMEENUM(SDL_SCANCODE_Y, 28)
            REGISTER_LIMEENUM(SDL_SCANCODE_Z, 29)
            REGISTER_LIMEENUM(SDL_SCANCODE_1, 30)
            REGISTER_LIMEENUM(SDL_SCANCODE_2, 31)
            REGISTER_LIMEENUM(SDL_SCANCODE_3, 32)
            REGISTER_LIMEENUM(SDL_SCANCODE_4, 33)
            REGISTER_LIMEENUM(SDL_SCANCODE_5, 34)
            REGISTER_LIMEENUM(SDL_SCANCODE_6, 35)
            REGISTER_LIMEENUM(SDL_SCANCODE_7, 36)
            REGISTER_LIMEENUM(SDL_SCANCODE_8, 37)
            REGISTER_LIMEENUM(SDL_SCANCODE_9, 38)
            REGISTER_LIMEENUM(SDL_SCANCODE_0, 39)
            REGISTER_LIMEENUM(SDL_SCANCODE_RETURN, 40)
            REGISTER_LIMEENUM(SDL_SCANCODE_ESCAPE, 41)
            REGISTER_LIMEENUM(SDL_SCANCODE_BACKSPACE, 42)
            REGISTER_LIMEENUM(SDL_SCANCODE_TAB, 43)
            REGISTER_LIMEENUM(SDL_SCANCODE_SPACE, 44)
            REGISTER_LIMEENUM(SDL_SCANCODE_MINUS, 45)
            REGISTER_LIMEENUM(SDL_SCANCODE_EQUALS, 46)
            REGISTER_LIMEENUM(SDL_SCANCODE_LEFTBRACKET, 47)
            REGISTER_LIMEENUM(SDL_SCANCODE_RIGHTBRACKET, 48)
            REGISTER_LIMEENUM(SDL_SCANCODE_BACKSLASH, 49)
            REGISTER_LIMEENUM(SDL_SCANCODE_NONUSHASH, 50)
            REGISTER_LIMEENUM(SDL_SCANCODE_SEMICOLON, 51)
            REGISTER_LIMEENUM(SDL_SCANCODE_APOSTROPHE, 52)
            REGISTER_LIMEENUM(SDL_SCANCODE_GRAVE, 53)
            REGISTER_LIMEENUM(SDL_SCANCODE_COMMA, 54)
            REGISTER_LIMEENUM(SDL_SCANCODE_PERIOD, 55)
            REGISTER_LIMEENUM(SDL_SCANCODE_SLASH, 56)
            REGISTER_LIMEENUM(SDL_SCANCODE_CAPSLOCK, 57)
            REGISTER_LIMEENUM(SDL_SCANCODE_F1, 58)
            REGISTER_LIMEENUM(SDL_SCANCODE_F2, 59)
            REGISTER_LIMEENUM(SDL_SCANCODE_F3, 60)
            REGISTER_LIMEENUM(SDL_SCANCODE_F4, 61)
            REGISTER_LIMEENUM(SDL_SCANCODE_F5, 62)
            REGISTER_LIMEENUM(SDL_SCANCODE_F6, 63)
            REGISTER_LIMEENUM(SDL_SCANCODE_F7, 64)
            REGISTER_LIMEENUM(SDL_SCANCODE_F8, 65)
            REGISTER_LIMEENUM(SDL_SCANCODE_F9, 66)
            REGISTER_LIMEENUM(SDL_SCANCODE_F10, 67)
            REGISTER_LIMEENUM(SDL_SCANCODE_F11, 68)
            REGISTER_LIMEENUM(SDL_SCANCODE_F12, 69)
            REGISTER_LIMEENUM(SDL_SCANCODE_PRINTSCREEN, 70)
            REGISTER_LIMEENUM(SDL_SCANCODE_SCROLLLOCK, 71)
            REGISTER_LIMEENUM(SDL_SCANCODE_PAUSE, 72)
            REGISTER_LIMEENUM(SDL_SCANCODE_INSERT, 73)
            REGISTER_LIMEENUM(SDL_SCANCODE_HOME, 74)
            REGISTER_LIMEENUM(SDL_SCANCODE_PAGEUP, 75)
            REGISTER_LIMEENUM(SDL_SCANCODE_DELETE, 76)
            REGISTER_LIMEENUM(SDL_SCANCODE_END, 77)
            REGISTER_LIMEENUM(SDL_SCANCODE_PAGEDOWN, 78)
            REGISTER_LIMEENUM(SDL_SCANCODE_RIGHT, 79)
            REGISTER_LIMEENUM(SDL_SCANCODE_LEFT, 80)
            REGISTER_LIMEENUM(SDL_SCANCODE_DOWN, 81)
            REGISTER_LIMEENUM(SDL_SCANCODE_UP, 82)
            REGISTER_LIMEENUM(SDL_SCANCODE_NUMLOCKCLEAR, 83)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_DIVIDE, 84)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MULTIPLY, 85)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MINUS, 86)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_PLUS, 87)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_ENTER, 88)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_1, 89)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_2, 90)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_3, 91)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_4, 92)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_5, 93)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_6, 94)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_7, 95)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_8, 96)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_9, 97)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_0, 98)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_PERIOD, 99)
            REGISTER_LIMEENUM(SDL_SCANCODE_NONUSBACKSLASH, 100)
            REGISTER_LIMEENUM(SDL_SCANCODE_APPLICATION, 101)
            REGISTER_LIMEENUM(SDL_SCANCODE_POWER, 102)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_EQUALS, 103)
            REGISTER_LIMEENUM(SDL_SCANCODE_F13, 104)
            REGISTER_LIMEENUM(SDL_SCANCODE_F14, 105)
            REGISTER_LIMEENUM(SDL_SCANCODE_F15, 106)
            REGISTER_LIMEENUM(SDL_SCANCODE_F16, 107)
            REGISTER_LIMEENUM(SDL_SCANCODE_F17, 108)
            REGISTER_LIMEENUM(SDL_SCANCODE_F18, 109)
            REGISTER_LIMEENUM(SDL_SCANCODE_F19, 110)
            REGISTER_LIMEENUM(SDL_SCANCODE_F20, 111)
            REGISTER_LIMEENUM(SDL_SCANCODE_F21, 112)
            REGISTER_LIMEENUM(SDL_SCANCODE_F22, 113)
            REGISTER_LIMEENUM(SDL_SCANCODE_F23, 114)
            REGISTER_LIMEENUM(SDL_SCANCODE_F24, 115)
            REGISTER_LIMEENUM(SDL_SCANCODE_EXECUTE, 116)
            REGISTER_LIMEENUM(SDL_SCANCODE_HELP, 117)
            REGISTER_LIMEENUM(SDL_SCANCODE_MENU, 118)
            REGISTER_LIMEENUM(SDL_SCANCODE_SELECT, 119)
            REGISTER_LIMEENUM(SDL_SCANCODE_STOP, 120)
            REGISTER_LIMEENUM(SDL_SCANCODE_AGAIN, 121)
            REGISTER_LIMEENUM(SDL_SCANCODE_UNDO, 122)
            REGISTER_LIMEENUM(SDL_SCANCODE_CUT, 123)
            REGISTER_LIMEENUM(SDL_SCANCODE_COPY, 124)
            REGISTER_LIMEENUM(SDL_SCANCODE_PASTE, 125)
            REGISTER_LIMEENUM(SDL_SCANCODE_FIND, 126)
            REGISTER_LIMEENUM(SDL_SCANCODE_MUTE, 127)
            REGISTER_LIMEENUM(SDL_SCANCODE_VOLUMEUP, 128)
            REGISTER_LIMEENUM(SDL_SCANCODE_VOLUMEDOWN, 129)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_COMMA, 133)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_EQUALSAS400, 134)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL1, 135)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL2, 136)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL3, 137)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL4, 138)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL5, 139)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL6, 140)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL7, 141)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL8, 142)
            REGISTER_LIMEENUM(SDL_SCANCODE_INTERNATIONAL9, 143)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG1, 144)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG2, 145)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG3, 146)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG4, 147)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG5, 148)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG6, 149)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG7, 150)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG8, 151)
            REGISTER_LIMEENUM(SDL_SCANCODE_LANG9, 152)
            REGISTER_LIMEENUM(SDL_SCANCODE_ALTERASE, 153)
            REGISTER_LIMEENUM(SDL_SCANCODE_SYSREQ, 154)
            REGISTER_LIMEENUM(SDL_SCANCODE_CANCEL, 155)
            REGISTER_LIMEENUM(SDL_SCANCODE_CLEAR, 156)
            REGISTER_LIMEENUM(SDL_SCANCODE_PRIOR, 157)
            REGISTER_LIMEENUM(SDL_SCANCODE_RETURN2, 158)
            REGISTER_LIMEENUM(SDL_SCANCODE_SEPARATOR, 159)
            REGISTER_LIMEENUM(SDL_SCANCODE_OUT, 160)
            REGISTER_LIMEENUM(SDL_SCANCODE_OPER, 161)
            REGISTER_LIMEENUM(SDL_SCANCODE_CLEARAGAIN, 162)
            REGISTER_LIMEENUM(SDL_SCANCODE_CRSEL, 163)
            REGISTER_LIMEENUM(SDL_SCANCODE_EXSEL, 164)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_00, 176)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_000, 177)
            REGISTER_LIMEENUM(SDL_SCANCODE_THOUSANDSSEPARATOR, 178)
            REGISTER_LIMEENUM(SDL_SCANCODE_DECIMALSEPARATOR, 179)
            REGISTER_LIMEENUM(SDL_SCANCODE_CURRENCYUNIT, 180)
            REGISTER_LIMEENUM(SDL_SCANCODE_CURRENCYSUBUNIT, 181)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_LEFTPAREN, 182)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_RIGHTPAREN, 183)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_LEFTBRACE, 184)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_RIGHTBRACE, 185)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_TAB, 186)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_BACKSPACE, 187)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_A, 188)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_B, 189)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_C, 190)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_D, 191)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_E, 192)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_F, 193)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_XOR, 194)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_POWER, 195)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_PERCENT, 196)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_LESS, 197)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_GREATER, 198)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_AMPERSAND, 199)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_DBLAMPERSAND, 200)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_VERTICALBAR, 201)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_DBLVERTICALBAR, 202)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_COLON, 203)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_HASH, 204)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_SPACE, 205)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_AT, 206)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_EXCLAM, 207)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMSTORE, 208)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMRECALL, 209)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMCLEAR, 210)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMADD, 211)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMSUBTRACT, 212)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMMULTIPLY, 213)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_MEMDIVIDE, 214)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_PLUSMINUS, 215)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_CLEAR, 216)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_CLEARENTRY, 217)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_BINARY, 218)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_OCTAL, 219)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_DECIMAL, 220)
            REGISTER_LIMEENUM(SDL_SCANCODE_KP_HEXADECIMAL, 221)
            REGISTER_LIMEENUM(SDL_SCANCODE_LCTRL, 224)
            REGISTER_LIMEENUM(SDL_SCANCODE_LSHIFT, 225)
            REGISTER_LIMEENUM(SDL_SCANCODE_LALT, 226)
            REGISTER_LIMEENUM(SDL_SCANCODE_LGUI, 227)
            REGISTER_LIMEENUM(SDL_SCANCODE_RCTRL, 228)
            REGISTER_LIMEENUM(SDL_SCANCODE_RSHIFT, 229)
            REGISTER_LIMEENUM(SDL_SCANCODE_RALT, 230)
            REGISTER_LIMEENUM(SDL_SCANCODE_RGUI, 231)
            REGISTER_LIMEENUM(SDL_SCANCODE_MODE, 257)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIONEXT, 258)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOPREV, 259)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOSTOP, 260)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOPLAY, 261)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOMUTE, 262)
            REGISTER_LIMEENUM(SDL_SCANCODE_MEDIASELECT, 263)
            REGISTER_LIMEENUM(SDL_SCANCODE_WWW, 264)
            REGISTER_LIMEENUM(SDL_SCANCODE_MAIL, 265)
            REGISTER_LIMEENUM(SDL_SCANCODE_CALCULATOR, 266)
            REGISTER_LIMEENUM(SDL_SCANCODE_COMPUTER, 267)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_SEARCH, 268)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_HOME, 269)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_BACK, 270)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_FORWARD, 271)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_STOP, 272)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_REFRESH, 273)
            REGISTER_LIMEENUM(SDL_SCANCODE_AC_BOOKMARKS, 274)
            REGISTER_LIMEENUM(SDL_SCANCODE_BRIGHTNESSDOWN, 275)
            REGISTER_LIMEENUM(SDL_SCANCODE_BRIGHTNESSUP, 276)
            REGISTER_LIMEENUM(SDL_SCANCODE_DISPLAYSWITCH, 277)
            REGISTER_LIMEENUM(SDL_SCANCODE_KBDILLUMTOGGLE, 278)
            REGISTER_LIMEENUM(SDL_SCANCODE_KBDILLUMDOWN, 279)
            REGISTER_LIMEENUM(SDL_SCANCODE_KBDILLUMUP, 280)
            REGISTER_LIMEENUM(SDL_SCANCODE_EJECT, 281)
            REGISTER_LIMEENUM(SDL_SCANCODE_SLEEP, 282)
            REGISTER_LIMEENUM(SDL_SCANCODE_APP1, 283)
            REGISTER_LIMEENUM(SDL_SCANCODE_APP2, 284)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOREWIND, 285)
            REGISTER_LIMEENUM(SDL_SCANCODE_AUDIOFASTFORWARD, 286)
            REGISTER_LIMEENUM(SDL_NUM_SCANCODES, 512)
    }
}



#endif

